version: "3.8"
services:

  frontend:
    image: assignment_4_frontend
    container_name: assignment_4_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command: npm start
    ports:
      - 3000:3000

  question_service:
    image: assignment_4_question_service
    container_name: assignment_4_question_service
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: npm run mongo
    ports:
      - 3002:3002
    expose:
      - '3002'
    environment:
      DB_URL: mongodb://db/peerprep

  profile_service:
    image: assignment_4_profile_service
    container_name: assignment_4_profile_service
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: npm run serve
    ports:
      - 3001:3001
    expose:
      - '3001'

  db:
    image: mongo:4.0-xenial
    ports:
      - 27017:27017